import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {

  const [lettuce, setLettuce] = useState(0)
  const [tomato, setTomato] = useState(0)
  const [beef, setBeef] = useState(0)
  const [bacon, setBacon] = useState(0)
  const [cheese, setCheese] = useState(0)

  function add(ingredient: number, setIngredient: Function) { setIngredient(ingredient + 1) }
  function remove(ingredient: number, setIngredient: Function) { setIngredient(ingredient - 1) }

  //for (i = 0, )
  const burgerContents: any = () => {

    let burger: any = []

    for (let i = 0; i < lettuce; i++) {
      burger.push(<div key={burger.length} className='lettuce'>Lettuce</div>)
      console.log(burger)
    }
    return burger
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{burgerContents()}</div>
        <div>
          <p>Lettuce</p>
          <button onClick={() => { add(lettuce, setLettuce) }}>I want more</button>
          <button onClick={() => { remove(lettuce, setLettuce) }}>I want less</button>
        </div>
      </main>
    </div>
  )
}
